### PR TITLE
Create ZombieEntityMixin.java

### PR DESCRIPTION
**Pull request by fxmorin**
I don't know if this is the way you write the Mixin. Made it pretty quick, it's a simple fix for drowned duping. All it does is not pass items from zombies to drowns when zombies get converted. Simple!

### CODE REVIEW

**Comment by fxmorin** [comment]
This was made pretty quick. It's untested.

**Comment by fxmorin** [comment]
I'll add the rule & mixin if you guys even want this for the skyblock

**Comment by DeadlyMC** [comment]
Also i don't want to harcode anything...so would be good if u could add it as a carpet rule

**Comment by fxmorin** [comment]
Ill make a new pull request for skyblock only

**Pull request closed without merging**
